package br.com.ss.centralaamar.model.entity;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profissao generated by hbm2java
 */
@Entity
@Table(name = "pastor", catalog = "centralaamar")
public class Pastor implements java.io.Serializable {

	private static final long serialVersionUID = 845836539746268610L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "past_id", unique = true, nullable = false)
	private Integer id;

	@Column(unique = true, nullable = false, length = 100)
	private String nome;

	public Pastor() {
	}

	public Pastor(String nome) {
		this.nome = nome;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}
