package br.ss.authenticator.model.entity;

// Generated 18/06/2012 13:32:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * PerfilRotina generated by hbm2java
 */
@Entity
@Table(name = "perfil_rotina", schema = "authenticator", uniqueConstraints = @UniqueConstraint(columnNames = { "id_perfil", "id_rotina" }))
public class PerfilRotina implements java.io.Serializable
{

   private int idPerfilRotina;
   private Rotina rotina;
   private Perfil perfil;
   private Date dtCadastro;

   public PerfilRotina()
   {
   }

   public PerfilRotina(int idPerfilRotina, Rotina rotina, Perfil perfil, Date dtCadastro)
   {
      this.idPerfilRotina = idPerfilRotina;
      this.rotina = rotina;
      this.perfil = perfil;
      this.dtCadastro = dtCadastro;
   }

   @Id
   @Column(name = "id_perfil_rotina", unique = true, nullable = false)
   public int getIdPerfilRotina()
   {
      return this.idPerfilRotina;
   }

   public void setIdPerfilRotina(int idPerfilRotina)
   {
      this.idPerfilRotina = idPerfilRotina;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_rotina", nullable = false)
   public Rotina getRotina()
   {
      return this.rotina;
   }

   public void setRotina(Rotina rotina)
   {
      this.rotina = rotina;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_perfil", nullable = false)
   public Perfil getPerfil()
   {
      return this.perfil;
   }

   public void setPerfil(Perfil perfil)
   {
      this.perfil = perfil;
   }

   @Temporal(TemporalType.DATE)
   @Column(name = "dt_cadastro", nullable = false, length = 13)
   public Date getDtCadastro()
   {
      return this.dtCadastro;
   }

   public void setDtCadastro(Date dtCadastro)
   {
      this.dtCadastro = dtCadastro;
   }

}
