package br.ss.authenticator.model.entity;

// Generated 11/07/2012 15:35:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;
import br.ss.core.model.entity.AbstractEntity;

/**
 * PerfilResponsabilidade generated by hbm2java
 */
@Entity
@Table(name = "perfil_responsabilidade", schema = "authenticator", 
		uniqueConstraints = @UniqueConstraint(columnNames = { "id_responsabilidade", "id_perfil" }))
@SequenceGenerator(name = "perfil_responsabilidade_id_perfil_responsabilidade_seq", 
					sequenceName = "authenticator.perfil_responsabilidade_id_perfil_responsabilidade_seq")
public class PerfilResponsabilidade extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -6550195806905698364L;
	
	@Getter @Setter
	@GeneratedValue(generator = "perfil_responsabilidade_id_perfil_responsabilidade_seq", strategy = GenerationType.SEQUENCE)
	@Id
	@Column(name = "id_perfil_responsabilidade", unique = true, nullable = false)
	private Integer idPerfilResponsabilidade;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_responsabilidade", nullable = false)
	private Responsabilidade responsabilidade;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false)
	private Perfil perfil;

	@Getter @Setter
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inicio", nullable = false, length = 29)
	private Date dtInicio;

	@Getter @Setter
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_termino", length = 29)
	private Date dtTermino;

	public PerfilResponsabilidade() { }

	public PerfilResponsabilidade(Integer idPerfilResponsabilidade,
			Responsabilidade responsabilidade, Perfil perfil, Date dtInicio) {
		this.idPerfilResponsabilidade = idPerfilResponsabilidade;
		this.responsabilidade = responsabilidade;
		this.perfil = perfil;
		this.dtInicio = dtInicio;
	}

	public PerfilResponsabilidade(Integer idPerfilResponsabilidade,
			Responsabilidade responsabilidade, Perfil perfil, Date dtInicio,
			Date dtTermino) {
		this.idPerfilResponsabilidade = idPerfilResponsabilidade;
		this.responsabilidade = responsabilidade;
		this.perfil = perfil;
		this.dtInicio = dtInicio;
		this.dtTermino = dtTermino;
	}

}
