package br.ss.authenticator.model.entity;

// Generated 11/07/2012 15:35:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;
import br.ss.core.model.entity.AbstractEntity;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name = "servico", schema = "authenticator")
@SequenceGenerator(name = "servico_id_servico_seq", sequenceName = "authenticator.servico_id_servico_seq")
public class Servico extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = 2573778066943168318L;
	
	@Getter @Setter
	@Id
	@GeneratedValue(generator = "servico_id_servico_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_servico", unique = true, nullable = false)
	private Integer idServico;
	
	@Getter @Setter
	@Column(name = "tx_servico", nullable = false, length = 80)
	private String txServico;

	@Getter @Setter
	@Column(name = "tx_servico_codigo", nullable = false, length = 40)
	private String txServicoCodigo;

	@Getter @Setter
	@Column(name = "tx_pacote_codigo", nullable = false, length = 20)
	private String txPacoteCodigo;
	
	@Getter @Setter
	@Column(name = "ativo", nullable = false)
	private Boolean ativo;

	public Servico() { }

	public Servico(Integer idServico, boolean ativo, String txServico, String txServicoCodigo, String txPacoteCodigo) {
		this.idServico = idServico;
		this.ativo = ativo;
		this.txServico = txServico;
		this.txServicoCodigo = txServicoCodigo;
		this.txPacoteCodigo = txPacoteCodigo;
	}

}
