package br.ss.authenticator.model.entity;

// Generated 18/06/2012 13:32:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;
import br.ss.core.model.entity.AbstractEntity;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "sistema", schema = "authenticator", uniqueConstraints = @UniqueConstraint(columnNames = "tx_sistema"))
@SequenceGenerator( name = "sistema_id_sistema_seq", sequenceName="authenticator.sistema_id_sistema_seq" )
public class Sistema extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = 469202678361230820L;

	@Getter @Setter
	@Id
	@GeneratedValue( generator = "sistema_id_sistema_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_sistema", unique = true, nullable = false)
	private Long idSistema;
	
	@Getter @Setter
	@Column(name = "tx_sistema", nullable = false, length = 50)
	private String txSistema;

	@Getter @Setter
	@Column(name = "tx_descricao", length = 100)
	private String txDescricao;

	@Getter @Setter
	@Column(name = "tx_sigla", nullable = false, length = 10)
	private String txSigla;

	@Getter @Setter
	@Column(name = "tx_url_home", nullable = false, length = 50)
	private String txUrlHome;
	
	@Setter @Getter 
	@Column(name = "ativo", nullable = false)
	private Boolean ativo;

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	private Set<Responsabilidade> responsabilidades = new HashSet<Responsabilidade>(0);
	
	public Sistema() { }

	public Sistema(Long idSistema, String txSistema, String txSigla, Boolean ativo) {
		this.idSistema = idSistema;
		this.txSistema = txSistema;
		this.txSigla = txSigla;
		this.ativo = ativo;
	}


	@Override
	public Long getId() {
		return getIdSistema();
	}

}
