package br.ss.authenticator.model.entity;

// Generated 18/06/2012 13:32:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * UsuarioPerfil generated by hbm2java
 */
@Entity
@Table(name = "usuario_perfil", schema = "authenticator", uniqueConstraints = @UniqueConstraint(columnNames = { "id_usuario", "id_perfil" }))
public class UsuarioPerfil implements java.io.Serializable
{

   private int idUsuarioPerfil;
   private Usuario usuario;
   private Perfil perfil;
   private Date dtCriacao;

   public UsuarioPerfil()
   {
   }

   public UsuarioPerfil(int idUsuarioPerfil, Usuario usuario, Perfil perfil)
   {
      this.idUsuarioPerfil = idUsuarioPerfil;
      this.usuario = usuario;
      this.perfil = perfil;
   }

   public UsuarioPerfil(int idUsuarioPerfil, Usuario usuario, Perfil perfil, Date dtCriacao)
   {
      this.idUsuarioPerfil = idUsuarioPerfil;
      this.usuario = usuario;
      this.perfil = perfil;
      this.dtCriacao = dtCriacao;
   }

   @Id
   @Column(name = "id_usuario_perfil", unique = true, nullable = false)
   public int getIdUsuarioPerfil()
   {
      return this.idUsuarioPerfil;
   }

   public void setIdUsuarioPerfil(int idUsuarioPerfil)
   {
      this.idUsuarioPerfil = idUsuarioPerfil;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_usuario", nullable = false)
   public Usuario getUsuario()
   {
      return this.usuario;
   }

   public void setUsuario(Usuario usuario)
   {
      this.usuario = usuario;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_perfil", nullable = false)
   public Perfil getPerfil()
   {
      return this.perfil;
   }

   public void setPerfil(Perfil perfil)
   {
      this.perfil = perfil;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "dt_criacao", length = 29)
   public Date getDtCriacao()
   {
      return this.dtCriacao;
   }

   public void setDtCriacao(Date dtCriacao)
   {
      this.dtCriacao = dtCriacao;
   }

}
