package br.ss.authenticator.model.entity;

// Generated 11/07/2012 15:35:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.ss.core.model.entity.AbstractEntity;

import lombok.Getter;
import lombok.Setter;

/**
 * UsuarioSenha generated by hbm2java
 */
@Entity
@Table(name = "usuario_senha", schema = "authenticator")
@SequenceGenerator(name = "usuario_senha_id_senha_seq", sequenceName = "authenticator.usuario_senha_id_senha_seq")
public class UsuarioSenha extends AbstractEntity implements java.io.Serializable {
	
	private static final long serialVersionUID = -410688253209653928L;
	
	@Getter @Setter
	@Id
	@GeneratedValue(generator = "usuario_senha_id_senha_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_senha", unique = true, nullable = false)
	private Integer idSenha;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false)
	private Usuario usuario;

	@Getter @Setter
	@Column(name = "tx_senha", nullable = false, length = 100)
	private String txSenha;

	@Getter @Setter
	@Temporal(TemporalType.DATE)
	@Column(name = "dt_senha", nullable = false, length = 13)
	private Date dtSenha;

	public UsuarioSenha() { }

	public UsuarioSenha(Integer idSenha, Usuario usuario, String txSenha,
			Date dtSenha) {
		this.idSenha = idSenha;
		this.usuario = usuario;
		this.txSenha = txSenha;
		this.dtSenha = dtSenha;
	}

}
