package br.ss.authenticator.model.entity;

// Generated 18/06/2012 13:32:57 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema = "authenticator", uniqueConstraints = @UniqueConstraint(columnNames = "tx_login"))
public class Usuario implements java.io.Serializable
{

   private int idUsuario;
   private String txLogin;
   private Date dtCadastro;
   private String txEmail;
   private String txSenha;
   private short csStatus;
   private Set<UsuarioPerfil> usuarioPerfils = new HashSet<UsuarioPerfil>(0);

   public Usuario()
   {
   }

   public Usuario(int idUsuario, String txLogin, Date dtCadastro, String txSenha, short csStatus)
   {
      this.idUsuario = idUsuario;
      this.txLogin = txLogin;
      this.dtCadastro = dtCadastro;
      this.txSenha = txSenha;
      this.csStatus = csStatus;
   }

   public Usuario(int idUsuario, String txLogin, Date dtCadastro, String txEmail, String txSenha, short csStatus, Set<UsuarioPerfil> usuarioPerfils)
   {
      this.idUsuario = idUsuario;
      this.txLogin = txLogin;
      this.dtCadastro = dtCadastro;
      this.txEmail = txEmail;
      this.txSenha = txSenha;
      this.csStatus = csStatus;
      this.usuarioPerfils = usuarioPerfils;
   }

   @Id
   @Column(name = "id_usuario", unique = true, nullable = false)
   public int getIdUsuario()
   {
      return this.idUsuario;
   }

   public void setIdUsuario(int idUsuario)
   {
      this.idUsuario = idUsuario;
   }

   @Column(name = "tx_login", unique = true, nullable = false, length = 11)
   public String getTxLogin()
   {
      return this.txLogin;
   }

   public void setTxLogin(String txLogin)
   {
      this.txLogin = txLogin;
   }

   @Temporal(TemporalType.TIMESTAMP)
   @Column(name = "dt_cadastro", nullable = false, length = 29)
   public Date getDtCadastro()
   {
      return this.dtCadastro;
   }

   public void setDtCadastro(Date dtCadastro)
   {
      this.dtCadastro = dtCadastro;
   }

   @Column(name = "tx_email", length = 60)
   public String getTxEmail()
   {
      return this.txEmail;
   }

   public void setTxEmail(String txEmail)
   {
      this.txEmail = txEmail;
   }

   @Column(name = "tx_senha", nullable = false, length = 100)
   public String getTxSenha()
   {
      return this.txSenha;
   }

   public void setTxSenha(String txSenha)
   {
      this.txSenha = txSenha;
   }

   @Column(name = "cs_status", nullable = false)
   public short getCsStatus()
   {
      return this.csStatus;
   }

   public void setCsStatus(short csStatus)
   {
      this.csStatus = csStatus;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
   public Set<UsuarioPerfil> getUsuarioPerfils()
   {
      return this.usuarioPerfils;
   }

   public void setUsuarioPerfils(Set<UsuarioPerfil> usuarioPerfils)
   {
      this.usuarioPerfils = usuarioPerfils;
   }

}
