package br.com.ss.centralaamar.model.dominio;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Membro generated by hbm2java
 */
@Entity
@Table(name = "cent_membro")
public class Membro extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -9176551890483396580L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mem_id", unique = true, nullable = false)
	private Long idMembro;

	@Column(name = "nome", nullable = false, length = 100, unique = true)
	private String nome;

	@Column(name = "endereco", length = 200)
	private String endereco;

	@Column(name = "bairro", length = 30)
	private String bairro;

	@Column(name = "celular", length = 12)
	private String celular;

	@Column(name = "fone_residencial", length = 12)
	private String foneResidencial;

	@Column(name = "fone_comercial", length = 12)
	private String foneComercial;

	// @Enumerated
	@Column(name = "sexo", nullable = false)
	// private MasculinoFemininoDomain sexo;e
	private String sexo;

	// @Enumerated
	@Column(name = "membro_igreja", nullable = false)
	// private SimNaoDomain membroIgreja;
	private String membroIgreja;

	@Temporal(TemporalType.DATE)
	@Column(name = "data_nascimento")
	private Date dataNascimento;

	@Column(name = "data_batismo")
	@Temporal(TemporalType.DATE)
	private Date dataBatismo;

	@Column(name = "email", length = 60)
	private String email;

	// @Enumerated
	@Column(name = "batizado")
	// private BatizadoDomain batizado;
	private String batizado;

	// @Enumerated
	@Column(name = "tem_filho")
	// private SimNaoDomain temFilho;
	private String temFilho;

	// @Enumerated
	@Column(name = "modo_conversao")
	// private ModoConversaoDomain modoConversao;
	private String modoConversao;

	@Column(name = "membros_batizado_familia", length = 255)
	private String membrosBatizadoFamilia;

	@Column(name = "pai", length = 100)
	private String pai;

	@Column(name = "mae", length = 100)
	private String mae;

	@Column(name = "amigo_contato", length = 100)
	private String amigoContato;

	@Column(name = "interesse", length = 50)
	private String interesse;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "pro_id", referencedColumnName = "pro_id")
	private Profissao profissao;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "peq_id", referencedColumnName = "peq_id")
	private PequenoGrupo pequenoGrupo;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "past_id", referencedColumnName = "past_id")
	private Pastor pastor;

	/* TODO chamada.. */
	//
	// @OneToMany(mappedBy = "membro", fetch = FetchType.LAZY)
	// @Fetch(FetchMode.SELECT)
	// @Cascade(CascadeType.SAVE_UPDATE)
	// private List<Chamada> chamadas = new ArrayList<Chamada>();

	public Membro() {
	}

	public Long getId() {
		return this.idMembro;
	}

	public Long getIdMembro() {
		return idMembro;
	}

	public void setIdMembro(Long idMembro) {
		this.idMembro = idMembro;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEndereco() {
		return endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	public String getBairro() {
		return bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	public String getFoneResidencial() {
		return foneResidencial;
	}

	public void setFoneResidencial(String foneResidencial) {
		this.foneResidencial = foneResidencial;
	}

	public String getFoneComercial() {
		return foneComercial;
	}

	public void setFoneComercial(String foneComercial) {
		this.foneComercial = foneComercial;
	}

	public String getSexo() {
		return sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	public String getMembroIgreja() {
		return membroIgreja;
	}

	public void setMembroIgreja(String membroIgreja) {
		this.membroIgreja = membroIgreja;
	}

	public Date getDataNascimento() {
		return dataNascimento;
	}

	public void setDataNascimento(Date dataNascimento) {
		this.dataNascimento = dataNascimento;
	}

	public Date getDataBatismo() {
		return dataBatismo;
	}

	public void setDataBatismo(Date dataBatismo) {
		this.dataBatismo = dataBatismo;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getBatizado() {
		return batizado;
	}

	public void setBatizado(String batizado) {
		this.batizado = batizado;
	}

	public String getTemFilho() {
		return temFilho;
	}

	public void setTemFilho(String temFilho) {
		this.temFilho = temFilho;
	}

	public String getModoConversao() {
		return modoConversao;
	}

	public void setModoConversao(String modoConversao) {
		this.modoConversao = modoConversao;
	}

	public String getMembrosBatizadoFamilia() {
		return membrosBatizadoFamilia;
	}

	public void setMembrosBatizadoFamilia(String membrosBatizadoFamilia) {
		this.membrosBatizadoFamilia = membrosBatizadoFamilia;
	}

	public String getPai() {
		return pai;
	}

	public void setPai(String pai) {
		this.pai = pai;
	}

	public String getMae() {
		return mae;
	}

	public void setMae(String mae) {
		this.mae = mae;
	}

	public String getAmigoContato() {
		return amigoContato;
	}

	public void setAmigoContato(String amigoContato) {
		this.amigoContato = amigoContato;
	}

	public String getInteresse() {
		return interesse;
	}

	public void setInteresse(String interesse) {
		this.interesse = interesse;
	}

	public Profissao getProfissao() {
		return profissao;
	}

	public void setProfissao(Profissao profissao) {
		this.profissao = profissao;
	}

	public PequenoGrupo getPequenoGrupo() {
		return pequenoGrupo;
	}

	public void setPequenoGrupo(PequenoGrupo pequenoGrupo) {
		this.pequenoGrupo = pequenoGrupo;
	}

	public Pastor getPastor() {
		return pastor;
	}

	public void setPastor(Pastor pastor) {
		this.pastor = pastor;
	}

}
