package br.ss.authenticator.model.entity;

// Generated 18/06/2012 13:32:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;
import br.ss.core.model.entity.AbstractEntity;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema = "authenticator", uniqueConstraints = @UniqueConstraint(columnNames = "tx_perfil"))
@SequenceGenerator(name = "perfil_id_perfil_seq", sequenceName = "authenticator.perfil_id_perfil_seq")
public class Perfil extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -8707502737221787297L;
	
	@Getter @Setter
	@GeneratedValue( generator = "perfil_id_perfil_seq", strategy = GenerationType.SEQUENCE )
	@Id
	@Column(name = "id_perfil", unique = true, nullable = false)
	private Long idPerfil;

	@Setter @Getter 
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	private Sistema sistema;

	@Getter @Setter
	@Column(name = "tx_perfil", unique = true, length = 100)
	private String txPerfil;

	@Setter @Getter 
	@Column(name = "ativo", nullable = false)
	private Boolean ativo;
	
	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	private Set<UsuarioPerfil> usuarioPerfils = new HashSet<UsuarioPerfil>(0);

	@Getter @Setter
	@OneToMany(fetch=FetchType.LAZY, mappedBy="perfil")
    private Set<PerfilResponsabilidade> perfilResponsabilidades = new HashSet<PerfilResponsabilidade>(0);
    
	public Perfil() { }

	public Perfil(Long idPerfil, Sistema sistema) {
		this.idPerfil = idPerfil;
		this.sistema = sistema;
	}

	public Perfil(Long idPerfil, Sistema sistema, String txPerfil,
					Set<UsuarioPerfil> usuarioPerfils) {
		this.idPerfil = idPerfil;
		this.sistema = sistema;
		this.txPerfil = txPerfil;
		this.usuarioPerfils = usuarioPerfils;
	}

}
