package br.ss.authenticator.model.entity;

// Generated 11/07/2012 15:35:00 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import lombok.Getter;
import lombok.Setter;
import br.ss.core.model.entity.AbstractEntity;

/**
 * Responsabilidade generated by hbm2java
 */
@Entity
@Table(name = "responsabilidade", schema = "authenticator", uniqueConstraints = @UniqueConstraint(columnNames = "tx_responsabilidade"))
@SequenceGenerator(name = "responsabilidade_id_responsabilidade_seq", sequenceName = "authenticator.responsabilidade_id_responsabilidade_seq")
public class Responsabilidade extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -235909449857593209L;

	@Getter @Setter
	@Id
	@GeneratedValue( generator = "responsabilidade_id_responsabilidade_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_responsabilidade", unique = true, nullable = false)
	private Integer idResponsabilidade;

	@Getter @Setter
	@Column(name = "tx_responsabilidade", nullable = false, length = 100)
	private String txResponsabilidade;

	@Getter @Setter
	@Column(name = "cs_ativo", nullable = false)
	private Boolean csAtivo;

	@Getter @Setter
	@Column(name = "tx_descricao", nullable = false, length = 300)
	private String txDescricao;

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsabilidade")
	private Set<ResponsabilidadeServico> responsabilidadeServicos = new HashSet<ResponsabilidadeServico>(0);

	@Getter @Setter
	@OneToMany(fetch=FetchType.LAZY, mappedBy="responsabilidade")
	private Set<PerfilResponsabilidade> perfilResponsabilidades = new HashSet<PerfilResponsabilidade>(0);

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "responsabilidade")
	private Set<UsuarioResponsaDesignada> usuarioResponsaDesignadas = new HashSet<UsuarioResponsaDesignada>(0);

	public Responsabilidade() { }

	public Responsabilidade(int idResponsabilidade, String txResponsabilidade,
			boolean csAtivo, String txDescricao) {
		this.idResponsabilidade = idResponsabilidade;
		this.txResponsabilidade = txResponsabilidade;
		this.csAtivo = csAtivo;
		this.txDescricao = txDescricao;
	}

	public Responsabilidade(int idResponsabilidade, String txResponsabilidade,
			boolean csAtivo, String txDescricao,
			Set<ResponsabilidadeServico> responsabilidadeServicos,
			Set<PerfilResponsabilidade> perfilResponsabilidades,
			Set<UsuarioResponsaDesignada> usuarioResponsaDesignadas) {
		this.idResponsabilidade = idResponsabilidade;
		this.txResponsabilidade = txResponsabilidade;
		this.csAtivo = csAtivo;
		this.txDescricao = txDescricao;
		this.responsabilidadeServicos = responsabilidadeServicos;
		this.perfilResponsabilidades = perfilResponsabilidades;
		this.usuarioResponsaDesignadas = usuarioResponsaDesignadas;
	}

}
