package br.ss.authenticator.model.entity;

// Generated 11/07/2012 15:35:00 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import br.ss.core.model.entity.AbstractEntity;

import lombok.Getter;
import lombok.Setter;

/**
 * Servico generated by hbm2java
 */
@Entity
@Table(name = "servico", schema = "authenticator")
@SequenceGenerator(name = "servico_id_servico_seq", sequenceName = "authenticator.servico_id_servico_seq")
public class Servico extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = 7698193340031361748L;
	
	@Getter @Setter
	@Id
	@GeneratedValue(generator = "servico_id_servico_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_servico", unique = true, nullable = false)
	private Integer idServico;
	
	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	private Sistema sistema;
	
	@Getter @Setter
	@Column(name = "ativo", nullable = false)
	private Boolean ativo;

	@Getter @Setter
	@Column(name = "tx_servico", nullable = false)
	private String txServico;

	public Servico() { }

	public Servico(Integer idServico, Sistema sistema, boolean ativo,
			String txServico) {
		this.idServico = idServico;
		this.sistema = sistema;
		this.ativo = ativo;
		this.txServico = txServico;
	}

}
