package br.ss.authenticator.model.entity;

// Generated 11/07/2012 15:35:00 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import br.ss.core.model.entity.AbstractEntity;

import lombok.Getter;
import lombok.Setter;

/**
 * UsuarioAcesso generated by hbm2java
 */
@Entity
@Table(name = "usuario_acesso", schema = "authenticator")
@SequenceGenerator(name = "usuario_acesso_id_usuario_acesso_seq", sequenceName = "authenticator.usuario_acesso_id_usuario_acesso_seq")
public class UsuarioAcesso extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = 6950410905522808936L;
	
	@Getter @Setter
	@Id
	@GeneratedValue(generator = "usuario_acesso_id_usuario_acesso_seq", strategy = GenerationType.SEQUENCE)
	@Column(name = "id_usuario_acesso", unique = true, nullable = false)
	private Integer idUsuarioAcesso;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_responsabilidade_servico", nullable = false)
	private ResponsabilidadeServico responsabilidadeServico;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_perfil")
	private UsuarioPerfil usuarioPerfil;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario_responsa_designada")
	private UsuarioResponsaDesignada usuarioResponsaDesignada;

	@Getter @Setter
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inicio", nullable = false, length = 29)
	private Date dtInicio;

	@Getter @Setter
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_fim", length = 29)
	private Date dtFim;

	public UsuarioAcesso() { }

	public UsuarioAcesso(int idUsuarioAcesso,
			ResponsabilidadeServico responsabilidadeServico, Date dtInicio) {
		this.idUsuarioAcesso = idUsuarioAcesso;
		this.responsabilidadeServico = responsabilidadeServico;
		this.dtInicio = dtInicio;
	}

	public UsuarioAcesso(int idUsuarioAcesso,
			ResponsabilidadeServico responsabilidadeServico,
			UsuarioPerfil usuarioPerfil,
			UsuarioResponsaDesignada usuarioResponsaDesignada, Date dtInicio,
			Date dtFim) {
		this.idUsuarioAcesso = idUsuarioAcesso;
		this.responsabilidadeServico = responsabilidadeServico;
		this.usuarioPerfil = usuarioPerfil;
		this.usuarioResponsaDesignada = usuarioResponsaDesignada;
		this.dtInicio = dtInicio;
		this.dtFim = dtFim;
	}

}
