package br.com.ss.centralaamar.model.entity;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pequenogrupo generated by hbm2java
 */
@Entity
@Table(name = "pequenogrupo", catalog = "centralaamar")
public class PequenoGrupo implements java.io.Serializable {

	private static final long serialVersionUID = -4554552668548180993L;
	
	private Integer id;
	private String descricao;

	public PequenoGrupo() {
	}

	public PequenoGrupo(String descricao) {
		this.descricao = descricao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peq_id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
