package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PerfilRotinaId generated by hbm2java
 */
@Embeddable
public class PerfilRotinaId implements java.io.Serializable {

	private int idPerfil;
	private int idRotina;

	public PerfilRotinaId() {
	}

	public PerfilRotinaId(int idPerfil, int idRotina) {
		this.idPerfil = idPerfil;
		this.idRotina = idRotina;
	}

	@Column(name = "id_perfil", nullable = false)
	public int getIdPerfil() {
		return this.idPerfil;
	}

	public void setIdPerfil(int idPerfil) {
		this.idPerfil = idPerfil;
	}

	@Column(name = "id_rotina", nullable = false)
	public int getIdRotina() {
		return this.idRotina;
	}

	public void setIdRotina(int idRotina) {
		this.idRotina = idRotina;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PerfilRotinaId))
			return false;
		PerfilRotinaId castOther = (PerfilRotinaId) other;

		return (this.getIdPerfil() == castOther.getIdPerfil())
				&& (this.getIdRotina() == castOther.getIdRotina());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdPerfil();
		result = 37 * result + this.getIdRotina();
		return result;
	}

}
