package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import lombok.Getter;
import lombok.Setter;

import br.ss.core.entity.AbstractEntity;
import br.ss.core.entity.NaturalIdentifier;

/**
 * Rotina generated by hbm2java
 */
@Entity
@Table(name = "rotina", schema="authenticator")
@SequenceGenerator( name="id_rotina_seq", sequenceName="authenticator.rotina_id_rotina_seq" )
public class Rotina implements java.io.Serializable {// extends AbstractEntity implements java.io.Serializable, NaturalIdentifier {
	
	@Id
	@GeneratedValue( generator="id_rotina_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_rotina", unique = true, nullable = false)
	@NotNull
	@Getter @Setter
	private Long id;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	@NotNull
	private Sistema sistema;

	@Getter @Setter
	@Column(name = "tx_rotina", nullable = false)
	@NotNull
	private String txRotina;

	@Getter @Setter
	@Column(name = "cs_status", nullable = false)
	private Boolean csStatus;

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rotina")
	private Set<PerfilRotina> perfilRotinas = new HashSet<PerfilRotina>(0);

	
	public Rotina() {
	}

	public Rotina(Long idRotina, Sistema sistema, String txRotina, Boolean csStatus) {
		this.id = idRotina;
		this.sistema = sistema;
		this.txRotina = txRotina;
		this.csStatus = csStatus;
	}

}
