package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.ss.core.entity.AbstractEntity;
import br.ss.core.entity.NaturalIdentifier;

import lombok.Getter;
import lombok.Setter;

/**
 * UsuarioPerfil generated by hbm2java
 */
@Entity
@Table(name = "usuario_perfil", schema="authenticator")
@SequenceGenerator( name="id_usuario_perfil_seq", sequenceName="authenticator.usuario_perfil_id_usuario_perfil_seq" )
public class UsuarioPerfil  extends AbstractEntity implements java.io.Serializable, NaturalIdentifier {

	@Id
    @Column( name = "id_usuario_perfil", unique = true, nullable = false )
    @GeneratedValue( strategy = GenerationType.AUTO, generator = "id_usuario_perfil_seq" )
    @NotNull
	@Getter @Setter
    private Long id;
	
	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false, insertable = false, updatable = false)
	@NotNull
	private Usuario usuario;

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	@NotNull
	private Perfil perfil;

	@Getter @Setter
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_criacao", length = 29)
	private Calendar dtCriacao;

	public UsuarioPerfil() {
	}

	public UsuarioPerfil( Usuario usuario, Perfil perfil, Calendar dtCriacao) {
		this.usuario = usuario;
		this.perfil = perfil;
		this.dtCriacao = dtCriacao;
	}

}
