package br.com.ss.centralaamar.model.dominio;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profissao generated by hbm2java
 */
@Entity
@Table(name = "cent_escolaSabatina")
public class EscolaSabatina extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = 845836539746268610L;

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "esco_id", nullable = false)
	private Long idEscolaSabatina;

	@Column(unique = true, nullable = false, length = 100)
	private String nome;

	public EscolaSabatina() {
	}

	public EscolaSabatina(String nome) {
		this.nome = nome;
	}

	@Override
	public Long getId() {
		return getIdEscolaSabatina();
	}

	public Long getIdEscolaSabatina() {
		return idEscolaSabatina;
	}

	public void setIdEscolaSabatina(Long idEscolaSabatina) {
		this.idEscolaSabatina = idEscolaSabatina;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

}