package br.com.ss.centralaamar.model.entity;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * Pequenogrupo generated by hbm2java
 */
@Entity
@Table(name = "pequenogrupo", catalog = "centralaamar")
public class PequenoGrupo extends AbstractEntity implements
		java.io.Serializable {

	private static final long serialVersionUID = -4554552668548180993L;

	@Getter
	@Setter
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peq_id", nullable = false)
	private Long idPequenoGrupo;

	@Getter
	@Setter
	@Column(unique = true, name = "nome", nullable = false, length = 100)
	private String nome;
	
	@Getter
	@Setter
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "anfi_id", referencedColumnName = "pro_id")
	private Membro anfritriao;

	public PequenoGrupo() {
	}

	public PequenoGrupo(String nome) {
		this.nome = nome;
	}

	@Override
	public Long getId() {
		return this.idPequenoGrupo;
	}

}
