package br.com.ss.centralaamar.model.entity;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import lombok.Getter;
import lombok.Setter;

/**
 * Pequenogrupo generated by hbm2java
 */
@Entity
@Table(name = "pequenogrupo", catalog = "centralaamar")
public class PequenoGrupo extends AbstractEntity implements java.io.Serializable {

	private static final long serialVersionUID = -4554552668548180993L;
	
	@Getter @Setter
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "peq_id", unique = true, nullable = false)
	private Long idPequenoGrupo;

	@Getter @Setter
	@Column(name = "descricao", nullable = false, length = 100)
	private String descricao;

	public PequenoGrupo() {
	}

	public PequenoGrupo(String descricao) {
		this.descricao = descricao;
	}

	@Override
	public Long getId() {
		return this.idPequenoGrupo;
	}

}
