package br.com.ss.centralaamar.model.entity;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Profissao generated by hbm2java
 */
@Entity
@Table(name = "profissao", catalog = "centralaamar")
public class Profissao implements java.io.Serializable {

	private static final long serialVersionUID = 845836539746268610L;
	
	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pro_id", unique = true, nullable = false)
	private Integer id;
	private String descricao;
	
//	@OneToMany(fetch = FetchType.LAZY)
//	private Set<Membro> membros = new HashSet<Membro>(0);

	public Profissao() {
	}

	public Profissao(String descricao) {
		this.descricao = descricao;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "descricao", nullable = false, length = 100)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

}
