package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.Calendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import br.ss.core.entity.AbstractEntity;
import br.ss.core.entity.NaturalIdentifier;

import lombok.Getter;
import lombok.Setter;

/**
 * PerfilRotina generated by hbm2java
 */
@Entity
@Table(name = "perfil_rotina", schema="authenticator")
@SequenceGenerator( name="id_perfil_rotina_seq", sequenceName="authenticator.perfil_rotina_id_perfil_rotina_seq" )
public class PerfilRotina implements java.io.Serializable {// extends AbstractEntity implements java.io.Serializable, NaturalIdentifier {

	@Id
    @Column( name = "id_perfil_rotina", unique = true, nullable = false )
    @GeneratedValue( strategy = GenerationType.AUTO, generator = "id_perfil_rotina_seq" )
    @NotNull
	@Getter @Setter
    private Long id;
	
    @Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rotina", nullable = false, insertable = false, updatable = false)
	@NotNull
	private Rotina rotina;

    @Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	@NotNull
	private Perfil perfil;

    @Getter @Setter
	@Temporal(TemporalType.DATE)
	@Column(name = "dt_cadastro", nullable = false, length = 13)
	@NotNull
	private Calendar dtCadastro;

	public PerfilRotina() {
	}

	public PerfilRotina(  Rotina rotina, Perfil perfil,
			Calendar dtCadastro) {
		this.rotina = rotina;
		this.perfil = perfil;
		this.dtCadastro = dtCadastro;
	}

}
