package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * PerfilRotina generated by hbm2java
 */
@Entity
@Table(name = "perfil_rotina", schema="authenticator")
public class PerfilRotina implements java.io.Serializable {

	private PerfilRotinaId id;
	private Rotina rotina;
	private Perfil perfil;
	private Date dtCadastro;

	public PerfilRotina() {
	}

	public PerfilRotina(PerfilRotinaId id, Rotina rotina, Perfil perfil,
			Date dtCadastro) {
		this.id = id;
		this.rotina = rotina;
		this.perfil = perfil;
		this.dtCadastro = dtCadastro;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idPerfil", column = @Column(name = "id_perfil", nullable = false)),
			@AttributeOverride(name = "idRotina", column = @Column(name = "id_rotina", nullable = false))})
	@NotNull
	public PerfilRotinaId getId() {
		return this.id;
	}

	public void setId(PerfilRotinaId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rotina", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Rotina getRotina() {
		return this.rotina;
	}

	public void setRotina(Rotina rotina) {
		this.rotina = rotina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_cadastro", nullable = false, length = 13)
	@NotNull
	public Date getDtCadastro() {
		return this.dtCadastro;
	}

	public void setDtCadastro(Date dtCadastro) {
		this.dtCadastro = dtCadastro;
	}

}
