package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import lombok.Getter;
import lombok.Setter;

import org.hibernate.validator.constraints.Length;

import br.ss.core.entity.AbstractEntity;
import br.ss.core.entity.NaturalIdentifier;

/**
 * Perfil generated by hbm2java
 */
@Entity
@Table(name = "perfil", schema="authenticator", uniqueConstraints = @UniqueConstraint(columnNames = "tx_perfil"))
@SequenceGenerator( name="id_perfil_seq", sequenceName="authenticator.perfil_id_perfil_seq" )
public class Perfil implements java.io.Serializable {// extends AbstractEntity implements java.io.Serializable, NaturalIdentifier {

	private static final long serialVersionUID = -6551667573438182659L;

	@Getter @Setter
	@Id
	@GeneratedValue( generator="id_perfil_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_perfil", unique = true, nullable = false)
	@NotNull
	private Long id;	

	@Getter @Setter
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	@NotNull
	private Sistema sistema;

	@Getter @Setter
	@Column(name = "tx_perfil", unique = true, length = 100)
	@Length(max = 100)
	private String txPerfil;

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	private Set<PerfilRotina> perfilRotinas = new HashSet<PerfilRotina>(0);

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "perfil")
	private Set<UsuarioPerfil> usuarioPerfils = new HashSet<UsuarioPerfil>(0);
	
	public Perfil() { }

	public Perfil(Long id , Sistema sistema, String txPerfil,
			Set<PerfilRotina> perfilRotinas, Set<UsuarioPerfil> usuarioPerfils) {
		this.id = id;
		this.sistema = sistema;
		this.txPerfil = txPerfil;
		this.perfilRotinas = perfilRotinas;
		this.usuarioPerfils = usuarioPerfils;
	}

}
