package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

/**
 * Rotina generated by hbm2java
 */
@Entity
@Table(name = "rotina", schema="authenticator")
@SequenceGenerator( name="id_rotina_seq", sequenceName="authenticator.rotina_id_rotina_seq" )
public class Rotina implements java.io.Serializable {

	private Integer idRotina;
	private Sistema sistema;
	private String txRotina;
	private Boolean csStatus;
	private Set<PerfilRotina> perfilRotinas = new HashSet<PerfilRotina>(0);

	public Rotina() {
	}

	public Rotina(Integer idRotina, Sistema sistema, String txRotina, Boolean csStatus) {
		this.idRotina = idRotina;
		this.sistema = sistema;
		this.txRotina = txRotina;
		this.csStatus = csStatus;
	}
	public Rotina(Integer idRotina, Sistema sistema, String txRotina,
			Boolean csStatus, Set<PerfilRotina> perfilRotinas) {
		this.idRotina = idRotina;
		this.sistema = sistema;
		this.txRotina = txRotina;
		this.csStatus = csStatus;
		this.perfilRotinas = perfilRotinas;
	}

	@Id
	@GeneratedValue( generator="id_rotina_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_rotina", unique = true, nullable = false)
	public Integer getIdRotina() {
		return this.idRotina;
	}

	public void setIdRotina(Integer idRotina) {
		this.idRotina = idRotina;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_sistema", nullable = false)
	@NotNull
	public Sistema getSistema() {
		return this.sistema;
	}

	public void setSistema(Sistema sistema) {
		this.sistema = sistema;
	}

	@Column(name = "tx_rotina", nullable = false)
	@NotNull
	public String getTxRotina() {
		return this.txRotina;
	}

	public void setTxRotina(String txRotina) {
		this.txRotina = txRotina;
	}

	@Column(name = "cs_status", nullable = false)
	public Boolean getCsStatus() {
		return this.csStatus;
	}

	public void setCsStatus(Boolean csStatus) {
		this.csStatus = csStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "rotina")
	public Set<PerfilRotina> getPerfilRotinas() {
		return this.perfilRotinas;
	}

	public void setPerfilRotinas(Set<PerfilRotina> perfilRotinas) {
		this.perfilRotinas = perfilRotinas;
	}

}
