package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.Length;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "sistema", schema="authenticator")
@SequenceGenerator( name="id_sistema_seq", sequenceName="authenticator.sistema_id_sistema_seq" )
public class Sistema implements java.io.Serializable {

	private Integer idSistema;
	private String txSistema;
	private String txDescricao;
	private String txSigla;
	private Set<Rotina> rotinas = new HashSet<Rotina>(0);
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	public Sistema() {
	}

	public Sistema(Integer idSistema, String txSistema, String txSigla) {
		this.idSistema = idSistema;
		this.txSistema = txSistema;
		this.txSigla = txSigla;
	}
	public Sistema(Integer idSistema, String txSistema, String txDescricao,
			String txSigla, Set<Rotina> rotinas, Set<Perfil> perfils) {
		this.idSistema = idSistema;
		this.txSistema = txSistema;
		this.txDescricao = txDescricao;
		this.txSigla = txSigla;
		this.rotinas = rotinas;
		this.perfils = perfils;
	}

	@Id
	@GeneratedValue( generator="id_sistema_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_sistema", unique = true, nullable = false)
	public Integer getIdSistema() {
		return this.idSistema;
	}

	public void setIdSistema(Integer idSistema) {
		this.idSistema = idSistema;
	}

	@Column(name = "tx_sistema", nullable = false, length = 50)
	@NotNull
	@Length(max = 50)
	public String getTxSistema() {
		return this.txSistema;
	}

	public void setTxSistema(String txSistema) {
		this.txSistema = txSistema;
	}

	@Column(name = "tx_descricao", length = 100)
	@Length(max = 100)
	public String getTxDescricao() {
		return this.txDescricao;
	}

	public void setTxDescricao(String txDescricao) {
		this.txDescricao = txDescricao;
	}

	@Column(name = "tx_sigla", nullable = false, length = 10)
	@NotNull
	@Length(max = 10)
	public String getTxSigla() {
		return this.txSigla;
	}

	public void setTxSigla(String txSigla) {
		this.txSigla = txSigla;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Rotina> getRotinas() {
		return this.rotinas;
	}

	public void setRotinas(Set<Rotina> rotinas) {
		this.rotinas = rotinas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	public Set<Perfil> getPerfils() {
		return this.perfils;
	}

	public void setPerfils(Set<Perfil> perfils) {
		this.perfils = perfils;
	}

}
