package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import lombok.Getter;
import lombok.Setter;

import org.hibernate.validator.constraints.Length;

import br.ss.core.entity.AbstractEntity;
import br.ss.core.entity.NaturalIdentifier;

/**
 * Sistema generated by hbm2java
 */
@Entity
@Table(name = "sistema", schema="authenticator")
@SequenceGenerator( name="id_sistema_seq", sequenceName="authenticator.sistema_id_sistema_seq" )
public class Sistema extends AbstractEntity implements java.io.Serializable, NaturalIdentifier {


	@Getter @Setter
	@Id
	@GeneratedValue( generator="id_sistema_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_sistema", unique = true, nullable = false)
	@NotNull
	private Long id;

	@Getter @Setter
	@Column(name = "tx_sistema", nullable = false, length = 50)
	@NotNull
	@Length(max = 50, message = "Nome do sistema deve ter no máximo 50 caracteres.")
	private String txSistema;

	@Getter @Setter
	@Column(name = "tx_descricao", length = 100)
	@Length(max = 100, message = "Descrição deve ter no máximo 100 caracteres.")
	private String txDescricao;

	@Getter @Setter
	@Column(name = "tx_sigla", nullable = false, length = 10)
	@NotNull
	@Length(max = 10, message = "Sigla deve ter no máximo 10 caracteres.")
	private String txSigla;

	@Getter @Setter
	@Column(name = "ativo", nullable = false )
	private boolean ativo;

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	private Set<Rotina> rotinas = new HashSet<Rotina>(0);

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sistema")
	private Set<Perfil> perfils = new HashSet<Perfil>(0);

	
	public Sistema() {
	}

	public Sistema(Long idSistema, String txSistema, String txDescricao,
			String txSigla, Set<Rotina> rotinas, Set<Perfil> perfils) {
		this.id = idSistema;
		this.txSistema = txSistema;
		this.txDescricao = txDescricao;
		this.txSigla = txSigla;
		this.rotinas = rotinas;
		this.perfils = perfils;
	}

}
