package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.Date;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

/**
 * UsuarioPerfil generated by hbm2java
 */
@Entity
@Table(name = "usuario_perfil", schema="authenticator")
public class UsuarioPerfil implements java.io.Serializable {

	private UsuarioPerfilId id;
	private Usuario usuario;
	private Perfil perfil;
	private Date dtCriacao;

	public UsuarioPerfil() {
	}

	public UsuarioPerfil(UsuarioPerfilId id, Usuario usuario, Perfil perfil) {
		this.id = id;
		this.usuario = usuario;
		this.perfil = perfil;
	}
	public UsuarioPerfil(UsuarioPerfilId id, Usuario usuario, Perfil perfil,
			Date dtCriacao) {
		this.id = id;
		this.usuario = usuario;
		this.perfil = perfil;
		this.dtCriacao = dtCriacao;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idUsuario", column = @Column(name = "id_usuario", nullable = false)),
			@AttributeOverride(name = "idPerfil", column = @Column(name = "id_perfil", nullable = false))})
	@NotNull
	public UsuarioPerfilId getId() {
		return this.id;
	}

	public void setId(UsuarioPerfilId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_usuario", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_perfil", nullable = false, insertable = false, updatable = false)
	@NotNull
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_criacao", length = 29)
	public Date getDtCriacao() {
		return this.dtCriacao;
	}

	public void setDtCriacao(Date dtCriacao) {
		this.dtCriacao = dtCriacao;
	}

}
