package br.ss.authenticator.model.entity;
// Generated 09/05/2012 21:23:25 by Hibernate Tools 3.2.4.GA

import java.util.Calendar;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import javax.validation.constraints.NotNull;

import lombok.Getter;
import lombok.Setter;

import org.hibernate.validator.constraints.Length;

import br.ss.core.entity.AbstractEntity;
import br.ss.core.entity.NaturalIdentifier;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario", schema="authenticator", uniqueConstraints = @UniqueConstraint(columnNames = "tx_login"))
@SequenceGenerator( name="id_usuario_seq", sequenceName="authenticator.usuario_id_usuario_seq" )
public class Usuario  extends AbstractEntity implements java.io.Serializable, NaturalIdentifier {

	@Getter @Setter
	@Id
	@GeneratedValue( generator="id_usuario_seq", strategy = GenerationType.SEQUENCE )
	@Column(name = "id_usuario", unique = true, nullable = false)
	private Long id;

	@Getter @Setter
	@Column(name = "tx_login", unique = true, nullable = false, length = 11)
	@NotNull
	@Length(max = 11)
	private String txLogin;

	@Getter @Setter
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_cadastro", nullable = false, length = 29)
	@NotNull
	private Calendar dtCadastro;

	@Getter @Setter
	@Column(name = "tx_email", length = 60)
	@Length(max = 60)
	private String txEmail;

	@Getter @Setter
	@Column(name = "tx_senha", nullable = false, length = 100)
	@NotNull
	@Length(max = 100)
	private String txSenha;

	@Getter @Setter
	@Column(name = "cs_status", nullable = false)
	private Short csStatus;

	@Getter @Setter
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "usuario")
	private Set<UsuarioPerfil> usuarioPerfils = new HashSet<UsuarioPerfil>(0);

	public Usuario() {
	}

	public Usuario(Long idUsuario, String txLogin, Calendar dtCadastro,
			String txSenha, Short csStatus) {
		this.id = idUsuario;
		this.txLogin = txLogin;
		this.dtCadastro = dtCadastro;
		this.txSenha = txSenha;
		this.csStatus = csStatus;
	}

}
