package br.com.ss.data.entities;

// Generated 02/12/2012 11:09:42 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.validator.constraints.Email;

/**
 * Membro generated by hbm2java
 */
@Entity
@Table(name = "igre_membro")
public class Membro implements java.io.Serializable {

	private static final long serialVersionUID = -1291295231738443097L;

	@Id
	@GeneratedValue(strategy = GenerationType.AUTO)
	private Integer id;

	private String nome;
	private String endereco;
	private String bairro;
	private String celular;
	private String foneResidencial;
	private String foneComercial;
	private String sexo;
	private String membroIgreja;
	private Date dataNascimento;
	private Date dataBatismo;
	private String email;
	private String batizado;
	private String temFilho;
	private String pai;
	private String mae;

	public Membro() {
	}

	public Membro(String nome, String endereco, String bairro, String sexo,
			String membroIgreja) {
		this.nome = nome;
		this.endereco = endereco;
		this.bairro = bairro;
		this.sexo = sexo;
		this.membroIgreja = membroIgreja;
	}

	public Integer getid() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 60)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "endereco", length = 60)
	public String getEndereco() {
		return this.endereco;
	}

	public void setEndereco(String endereco) {
		this.endereco = endereco;
	}

	@Column(name = "bairro", length = 30)
	public String getBairro() {
		return this.bairro;
	}

	public void setBairro(String bairro) {
		this.bairro = bairro;
	}

	@Column(name = "celular", length = 10)
	public String getCelular() {
		return this.celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "foneResidencial", length = 10)
	public String getFoneResidencial() {
		return this.foneResidencial;
	}

	public void setFoneResidencial(String foneResidencial) {
		this.foneResidencial = foneResidencial;
	}

	@Column(name = "foneComercial", length = 10)
	public String getFoneComercial() {
		return this.foneComercial;
	}

	public void setFoneComercial(String foneComercial) {
		this.foneComercial = foneComercial;
	}

	@Column(name = "sexo", nullable = false, length = 1)
	public String getSexo() {
		return this.sexo;
	}

	public void setSexo(String sexo) {
		this.sexo = sexo;
	}

	@Column(name = "membroIgreja", nullable = false, length = 1)
	public String getMembroIgreja() {
		return this.membroIgreja;
	}

	public void setMembroIgreja(String membroIgreja) {
		this.membroIgreja = membroIgreja;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dataNascimento")
	public Date getDataNascimento() {
		return this.dataNascimento;
	}

	public void setDataNascimento(Date dataNacimento) {
		this.dataNascimento = dataNacimento;
	}

	@Column(name = "email", length = 60)
	@Email(message = "E-mail inválido!")
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Integer getId() {
		return id;
	}

	public String getBatizado() {
		return batizado;
	}

	public void setBatizado(String batizado) {
		this.batizado = batizado;
	}

	public Date getDataBatismo() {
		return dataBatismo;
	}

	public void setDataBatismo(Date dataBatismo) {
		this.dataBatismo = dataBatismo;
	}

	public String getTemFilho() {
		return temFilho;
	}

	public void setTemFilho(String temFilho) {
		this.temFilho = temFilho;
	}

	public String getPai() {
		return pai;
	}

	public void setPai(String pai) {
		this.pai = pai;
	}

	public String getMae() {
		return mae;
	}

	public void setMae(String mae) {
		this.mae = mae;
	}

}