package br.ss.authenticator.model.entity;

// Generated 18/06/2012 13:32:57 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Rotina generated by hbm2java
 */
@Entity
@Table(name = "rotina", schema = "authenticator")
public class Rotina implements java.io.Serializable
{

   private int idRotina;
   private Sistema sistema;
   private String txRotina;
   private boolean csStatus;
   private Set<PerfilRotina> perfilRotinas = new HashSet<PerfilRotina>(0);

   public Rotina()
   {
   }

   public Rotina(int idRotina, Sistema sistema, String txRotina, boolean csStatus)
   {
      this.idRotina = idRotina;
      this.sistema = sistema;
      this.txRotina = txRotina;
      this.csStatus = csStatus;
   }

   public Rotina(int idRotina, Sistema sistema, String txRotina, boolean csStatus, Set<PerfilRotina> perfilRotinas)
   {
      this.idRotina = idRotina;
      this.sistema = sistema;
      this.txRotina = txRotina;
      this.csStatus = csStatus;
      this.perfilRotinas = perfilRotinas;
   }

   @Id
   @Column(name = "id_rotina", unique = true, nullable = false)
   public int getIdRotina()
   {
      return this.idRotina;
   }

   public void setIdRotina(int idRotina)
   {
      this.idRotina = idRotina;
   }

   @ManyToOne(fetch = FetchType.LAZY)
   @JoinColumn(name = "id_sistema", nullable = false)
   public Sistema getSistema()
   {
      return this.sistema;
   }

   public void setSistema(Sistema sistema)
   {
      this.sistema = sistema;
   }

   @Column(name = "tx_rotina", nullable = false)
   public String getTxRotina()
   {
      return this.txRotina;
   }

   public void setTxRotina(String txRotina)
   {
      this.txRotina = txRotina;
   }

   @Column(name = "cs_status", nullable = false)
   public boolean isCsStatus()
   {
      return this.csStatus;
   }

   public void setCsStatus(boolean csStatus)
   {
      this.csStatus = csStatus;
   }

   @OneToMany(fetch = FetchType.LAZY, mappedBy = "rotina")
   public Set<PerfilRotina> getPerfilRotinas()
   {
      return this.perfilRotinas;
   }

   public void setPerfilRotinas(Set<PerfilRotina> perfilRotinas)
   {
      this.perfilRotinas = perfilRotinas;
   }

}
